---
- name: Remove stale data from /etc/hosts if exist
  lineinfile:
    dest: '/etc/hosts'
    regexp: '{{ hostvars[item].inventory_hostname }}'
    state: absent
  with_items: "{{ groups.all }}"
  when: "[hostvars[item].ansible_ssh_host] | ipv4"

- name: Update /etc/hosts with new cluster nodes
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_ssh_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"
  when: "[hostvars[item].ansible_ssh_host] | ipv4"

- name: Create directory for dnsmasq config file if absent
  file:
    dest: /etc/dnsmasq.d
    state: directory
    mode: 0644

- name: Create custom dnsmasq config file for current cluster
  file:
    dest: '/etc/dnsmasq.d/openshift-cluster-{{ cluster_id }}.conf'
    state: touch

- name: Remove stale data from custom dnsmasq config file is exist
  lineinfile:
    dest: '/etc/dnsmasq.d/openshift-cluster-{{ cluster_id }}.conf'
    regexp: "{{ hostvars[item].inventory_hostname_short }}"
    state: absent
  with_items: "{{ groups.all }}"
  when: "[hostvars[item].ansible_ssh_host] | ipv4"

- name: Write data to custom dnsmasq config file
  lineinfile:
    dest: '/etc/dnsmasq.d/openshift-cluster-{{ cluster_id }}.conf'
    line: "address=/{{ hostvars[item].inventory_hostname_short }}/{{ hostvars[item].ansible_ssh_host }}"
    state: present
  with_items: "{{ groups.all }}"
  when: "[hostvars[item].ansible_ssh_host] | ipv4"
