---
- name: Add mapping of new domain names of the cluster nodes to each other
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_ssh_host }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups.all }}"
  when: "[hostvars[item].ansible_ssh_host] | ipv4"
